### ISSUE TITLE
Slic3r não lida com nomes de perfil em unicode

### ISSUE THREAD

**Issue by rodrigopitanga** [Metamaquina/Printrun#12]
O Slic3r (GUI) não lida bem com os nomes de perfil com acento. 

Slic3r 0.9.10-dev (o que está sendo distribuído no nosso release)
Trisquel GNU/Linux 6.0
Os perfis que estão no git tem acento no nome, e não funcionam.
Notei que os que foram no release não tem acento, então provavelmente isso foi percebido.

Típico bug upstream. Estou registrando aqui para testarmos no atual e depois reportarmos.

**Comment by felipesanches** [comment]
Sim, foi exatamente isso que aconteceu. Até reportei um bug sobre isso. https://github.com/Metamaquina/Printrun/issues/3

**Comment by rodrigopitanga** [comment]
> Sim, foi exatamente isso que aconteceu. Até reportei um bug sobre
>   isso. https://github.com/Metamaquina/Printrun/issues/3

Ah, não tinha visto!
