### ISSUE TITLE
Versão do Slic3r distribuída no release

### ISSUE THREAD

**Issue by rodrigopitanga** [Metamaquina/Printrun#13]
Pelo que entendi aqui é a 0.9.10-dev (checkout do git de um dia x)

Acho que não é uma boa prática distribuir versão de desenvolvimento junto com o que, teoricamente, deve ser estável.

Inclusive tem um .gitignore no release.

**Comment by felipesanches** [comment]
Retirei a versão de desenvolvimento e coloquei um build estável para x86 32 bits. O próximo passo é fazermos um bundle para cada arquitetura (32bits e 64bits), mas isso é outra issue: https://github.com/Metamaquina/Printrun/issues/20
