### ISSUE TITLE
Jogmode não aparece no bundle para w32/w64

### ISSUE THREAD

**Issue by rodrigopitanga** [Metamaquina/Printrun#18]

**Comment by felipesanches** [comment]
Isso parece ser um bug de empacotamento no Windows. Tudo que é imagem não está aparecendo. O gráfico de temperatura também não aparece.

**Comment by rodrigopitanga** [comment]
E aí?

**Comment by felipesanches** [comment]
O pronterface não exibe o jog panel mesmo antes de ser empacotado. Portanto não parece ser um bug de empacotamento. Deve ser bug de alguma versão específica de alguma dependência. Um caminho para tentar solucionar isso é descobrir qual biblioteca é usada para a renderização das imagens. Talvez seja a própria wx-python. Ou talvez seja algo mais baixo nível como a libcairo ou algo similar.

**Comment by felipesanches** [comment]
De todo modo, há um pull request no upstream de um script de empacotamento:

https://github.com/kliment/Printrun/pull/421

Ele usa o py2exe também, então deve ser similar ao nosso. Não vai solucionar o problema do jog panel, mas pode ser um script melhor do que o que a gente fez do zero.

**Comment by felipesanches** [comment]
Este bundle pré-compilado exibe o jog panel:
http://koti.kapsi.fi/~kliment/printrun/Printrun-Win-Slic3r-12July2013.zip

Mas não sei qual foi o procedimento que ele usou para empacotar.

**Comment by rodrigopitanga** [comment]
Em todas as instalações que fiz no windows (instalando todas as
dependências na mão, de acordo com o manual da mm beta), o jog panel
apareceu.

**Comment by felipesanches** [comment]
Corrigi o problema. Lancei um bundle novo pra Windows contendo a correção.
