### ISSUE TITLE
Fill density não é setado corretamente

### ISSUE THREAD

**Issue by rodrigopitanga** [Metamaquina/Printrun#45]
Temos alguns casos de clientes (Windows) em que o Fill Density não é inicializado em uma instalação fresh. Provavelmente é um bug do último release p/ windows.

**Comment by rodrigopitanga** [comment]
![erro load file](https://f.cloud.github.com/assets/1755608/1054543/a7d2efbc-110b-11e3-9c5f-ea232eaeaee0.png)

**Comment by felipesanches** [comment]
Corrigido. O problema era o uso de %s na string de fatiamento default. (que obviamente não passa por substituição de variáveis)
