### ISSUE TITLE
Schermann

### ISSUE THREAD

**Issue by gui7vaz** [Metamaquina/Printrun#49]
Número de Série "40"

Guilherme, boa noite.

Fiz pouco uso da minha máquina e estou enfrentando alguns problemas. Escrevo para pedir a ajuda de vocês.

Tenho pouco tempo disponível para os meus projetos "professor pardal", então praticamente não fiz uso da máquina ainda, mas acredito que ela esteja com algum problema, possivelmente no servo motor que cuida da extrusão, ou nos que movem os eixos x e y.

Quando a máquina chegou, segui o passo a passo do site, desembalei, conectei os cabos, instalei o driver e fiz o download do pronterface.

Como indicado no passo a passo, fiz a configuração do eixo z e depois imprimi a peça de teste. O resultado foi muito bacana, achei a qualidade muito boa para uma máquina de custo tão baixo (vide anexo 1).

Depois disso, também imprimi um busto do Yoada e também fiquei satisfeito com o resultado. A resolução não é "premium", mas para uma máquina básica achei muito bom, fiquei bem satisfeito. (vide anexo 2)

Então passei vários dias sem utilizar a máquina e quando fui utilizar, novamente imprimi a peça teste, para ver se estava tudo ok, e a impressão ficou ótima como a primeira (vide anexo 3). 

Então fui imprimir peças de um dos meus projetos. A primeira peça foi impressa com perfeição, não deixando nada a desejar em relação à qualidade das demais (vide anexo 4).

Foi com a impressão da segunda peça, entretanto, que os problemas começaram. Essa segunda peça era uma peça maior, consistindo de um tubo de 10cm de altura com 8 cm de diâmetro e paredes de 5mm. A impressão começou muto bem, com o mesmo nível de qualidade, mas quando a peça estava com uns 7,5cm de altura a impressão começou a ficar muito ruim. A impressão começou a ficar muito porosa, como se não estivessem sendo impressas todas as camadas ou se a impressora já não estivesse conseguindo fazer os gomos da "colméia" adequadamente. Nessa hora, eu comecei a notar um estalo estranho no servo motor do extrusor, como se a engrenagem estivesse emperrando. Não sei se normalmente faz esse barulho, mas ele só me chamou a atenção quando a impressão começou a ficar muito ruim. (Vide o vídeo anexo, que fiz no momento da impressão, em que é possível perceber tanto a queda na qualidade da impressão - é bastante visível - quanto o dito barulho. Dá para ver a engrenagem "pulando" um pouco também).

Eu não sei exatamente porque isso aconteceu, mas a minha impressão é que algum dos servo motores não tenha aguentado o tranco e tenha passado a apresentar problemas em razão da impressão mais demorada, por se tratar de uma peça grande (a maior que eu tentei imprimir). Por causa do barulho que você poderá ver no vídeo, suspeito principalmente do servo motor do extrusor, embora possa ser algum outro problema.

O fato é que depois desse episódio, não consegui imprimir mais nada com o mínimo de qualidade. Nem mesmo a peça de teste. As impressões posteriores a esse evento tem uma qualidade muito baixa, principalmente no acabamento da superfície, bastante poroso e irregular, sendo que algumas ficaram até mesmo irreconhecíveis (veja demais anexos).

Não preciso nem dizer que estou bastante frustrado, né? Estou fazendo essa descrição detalhada, anexando as fotos e o vídeo, para que vocês possam, com base na experiência de vocês, avaliar qual seja o problema. Vocês podem dar uma olhada e me retornar asap?

Muito obrigado!

Link para os anexos:

Arquivo Metamáquina - https://drive.google.com/folderview?id=0B1fgKHRF32XASGlxYzJRRXpyb2s&usp=sharing 

Um grande abraço,
Schermann Chrystie.

**Comment by felipesanches** [comment]
Guilherme, 

Não devemos citar os nomes e dificuldades de clientes em público. Já temos nosso sistema interno de suporte técnico para tratar esses casos.

Além disso, issues no GitHub devem ser relativas a algum problema específico do software. No caso deste repositório deve ser específico a respeito de bugs do Pronterface. Descrições genéricas de dificuldades de usuários específicos não são úteis em um bugtracker. 

Estou fechando esta issue. Caso seja necessário abra issues individuais para cada problema individual identificado e que possa ser um ponto de partida para o time de desenvolvimento implementar melhorias no produto. Tome cuidado para cadastrar as issues no bug tracker correto. Temos este para o Pronterface, mas temos também um issue tracker para o Repetier-Firwmware e outro para o hardware da Metamáquina 2.
