### ISSUE TITLE
Pergunta "Tem certeza que deseja cancelar a impressão"

### ISSUE THREAD

**Issue by danieldonadel** [Metamaquina/Printrun#50]
Quando você tenta minimizar o pronterface no meio da impressão, mas sua pressa clica no "x" de fechar janela, você perde a impressão.
Sugestão de sempre que for abortar a impressão por qualquer botão perguntar antes da sobriedade do ato.

**Comment by rodrigopitanga** [comment]
Falta traduzir para o PT_BR
