### ISSUE TITLE
Perfil de impressão - Sugestões

### ISSUE THREAD

**Issue by gui7vaz** [Metamaquina/Printrun#51]
Só algumas ideias:

1) Remover a opção - Infill only where needed 
Esta opção deixa habilitado a formação de preenchimento interno da peça somente onde é necessário, ou seja, nos lugares que possuem algum tipo de "teto".

2) Aumentar o número de loops do skirt
Hoje por padrão está setado para 2 loops. Eu aconselho 5 loops. 
a) Ponto a favor: 
i) para todas as peças: usuário terá tempo de calibrar a base
ii) para as peças pequenas: vai dar tempo de calibrar e limpar o bico. 
b) Ponto Contra:
i) Para as peças grandes: vai demorar muito, a impressora vai imprimir muita saia.
ii) para as peças grandes (20x20): não sei como o slic3r se comporta, mas vale a pena estudar o seguinte: o skirt é setado para ficar afastado 10mm das peças, mas no caso de peças com 20mm ele ultrapassa a área de impressão, o que ocorre?

3) Sugerir para o alexrj ou mesmo criar algum código que leia o perímetro do skirt e escolha automaticamente a quantidade de loops.

4) colocar no end g-code o código m908 p3 s110 para diminuir a quantidade de corrente do motor.

5) Mudar o nome de saída do arquivo. hj está setado para [input_filename_base]_s3r.gcode 
sugiro que mude para 
Metamaquina_[input_filename_base].gcode
ou 
[input_filename_base]_para impressao.gcode
enfim.. algo do tipo.

**Comment by rodrigopitanga** [comment]
Fechando e criando tickets menores.
